routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Web'], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::post('', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');


    // Admin
    Route::group(
        [
            'middleware'    => 'web.admin',
            'prefix'        => 'admin',
            'namespace'     => 'Admin',
            'as'            => 'admin.'
        ],
        function ()
        {
            Route::get('', 'HomeController@index')->name('index');

            // Users
            Route::group(
                [
                    'prefix'    => 'users',
                    'as'        => 'users.'
                ],
                function () {
                    Route::get('', 'UserController@index')->name('index');
                    Route::get('edit/{id}', 'UserController@edit')->name('edit');
                    Route::post('edit/{id}', 'UserController@update');
                }
            );

            // Categories
            Route::group(
                [
                    'prefix'    => 'categories',
                    'as'        => 'categories.'
                ],
                function () {
                    Route::get('', 'CategoryController@index')->name('index');
                    Route::get('show/{id}', 'CategoryController@show')->name('show');
                    Route::get('create', 'CategoryController@create')->name('create');
                    Route::post('create', 'CategoryController@store');
                    Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
                    Route::post('edit/{id}', 'CategoryController@update');

                    // Attributes
                    Route::group(
                        [
                            'prefix'    => 'attributes/{category_id}',
                            'as'        => 'attributes.'
                        ],
                        function () {
                            Route::get('', 'CategoryAttributeController@index')->name('index');
                            Route::get('create', 'CategoryAttributeController@create')->name('create');
                            Route::post('create', 'CategoryAttributeController@store');
                            Route::get('edit/{id}', 'CategoryAttributeController@edit')->name('edit');
                            Route::post('edit/{id}', 'CategoryAttributeController@update');
                        }
                    );
                }
            );

            // Products
            Route::group(
                [
                    'prefix'    => 'products',
                    'as'        => 'products.'
                ],
                function () {
                    Route::get('create', 'ProductController@create')->name('create');
                    Route::post('create', 'ProductController@store');
                    Route::get('edit/{id}', 'ProductController@edit')->name('edit');
                    Route::post('edit/{id}', 'ProductController@update');
                    Route::get('delete-image/{id}', 'ProductController@deleteImage')->name('delete-image');

                    // Attributes
                    Route::group(
                        [
                            'prefix'    => 'attributes/{product_id}',
                            'as'        => 'attributes.'
                        ],
                        function () {
                            Route::get('', 'ProductAttributeController@index')->name('index');
                            Route::post('', 'ProductAttributeController@save');
                        }
                    );
                }
            );
        }
    );
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Category
 * @package App\Models
 * @property int $id
 * @property string $name
 * @property string $icon
 */
class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'icon'
    ];

    /**
     * @return BelongsToMany
     */
    public function attributes(): BelongsToMany
    {
        return $this->belongsToMany(Attribute::class);
    }

    /**
     * @return HasMany
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Web/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Web\Admin\Category\CreateRequest;
use App\Http\Requests\Web\Admin\Category\UpdateRequest;
use App\Models\Category;
use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;
use DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    /**
     * @var ProductRepository
     */
    private $productRepository;

    /**
     * CategoryController constructor.
     */
    public function __construct()
    {
        $this->categoryRepository = app(CategoryRepository::class);
        $this->productRepository = app(ProductRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = $this->categoryRepository
            ->getAllWithPaginate(10);

        return view('admin.categories.index', [
            'categories'    => $categories,
            'title'         => 'Каталог'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('admin.categories.create', [
            'title' => 'Добавление категории'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateRequest  $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $data = $request->validated();

        Category::create($data);

        return redirect()
            ->route('admin.categories.index')
            ->with('success', 'Категория добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View|RedirectResponse
     */
    public function show(int $id)
    {
        $category = $this->categoryRepository
            ->firstForEdit($id);

        if (empty($category)) {
            return redirect()
                ->route('admin.categories.index')
                ->with('error', 'Категория не найдена');
        }

        $products = $this->productRepository
            ->getByCategoryId($category->id, 10);

        Breadcrumbs::setCurrentRoute('admin.categories.show', $category->name);

        return view('admin.categories.show', [
            'category'  => $category,
            'products'  => $products,
            'title'     => 'Категория ' . $category->name
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View|RedirectResponse
     */
    public function edit(int $id)
    {
        $category = $this->categoryRepository
            ->firstForEdit($id);

        if (empty($category)) {
            return redirect()
                ->route('admin.categories.index')
                ->with('error', 'Категория не найдена');
        }

        return view('admin.categories.edit', [
            'category'  => $category,
            'title'     => 'Редактирование категории'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateRequest  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, int $id)
    {
        $category = $this->categoryRepository
            ->firstForEdit($id);

        if (empty($category)) {
            return redirect()
                ->route('admin.categories.index')
                ->with('error', 'Категория не найдена');
        }

        $data = $request->validated();
        $category->update($data);

        return redirect()
            ->route('admin.categories.index')
            ->with('success', 'Изменения сохранены');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2><strong>{{ $title }}</strong></h2>
                </div>
                <div class="body">
                    <form method="POST" enctype="multipart/form-data">
                        @csrf
                        <label for="name">Название</label>
                        <div class="form-group">
                            @error('name')
                            <label class="error" for="name">{{ $message }}</label>
                            @enderror
                            <input type="text" id="name" value="{{ old('name') }}" name="name" class="form-control" required>
                        </div>

                        <label for="icon">Иконка</label>
                        <div class="form-group">
                            @error('icon')
                            <label class="error" for="icon">{{ $message }}</label>
                            @enderror
                            <input type="file" name="icon" id="icon" class="dropify" data-allowed-file-extensions="png jpg jpeg" required>
                        </div>

                        <button type="submit" class="btn btn-raised btn-primary btn-round waves-effect">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2><strong>{{ $title }}</strong></h2>
                </div>
                <div class="body">
                    <form method="POST" enctype="multipart/form-data">
                        @csrf
                        <label for="name">Название</label>
                        <div class="form-group">
                            @error('name')
                            <label class="error" for="name">{{ $message }}</label>
                            @enderror
                            <input type="text" id="name" value="{{ old('name', $category->name) }}" name="name" class="form-control" required>
                        </div>

                        <label for="icon">Иконка</label>
                        <div class="form-group">
                            @error('icon')
                            <label class="error" for="icon">{{ $message }}</label>
                            @enderror
                            <input type="file" name="icon" id="icon" class="dropify" data-allowed-file-extensions="png jpg jpeg" @if($category->icon) data-default-file="{{ $category->icon }}" @endif>
                        </div>

                        <button type="submit" class="btn btn-raised btn-primary btn-round waves-effect">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2><strong>{{ $title }}</strong></h2>
                    <br>
                    <h2><a href="{{ route('admin.categories.create') }}" class="btn btn-light">Добавить категорию</a></h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="text-left">#</th>
                                <th>Название</th>
                                <th>Иконка</th>
                                <th class="text-right">
                                    <i class="zmdi zmdi-settings"></i>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td class="text-left">{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                        <img src="{{ $category->icon }}" alt="" width="100">
                                    </td>
                                    <td class="text-right">
                                        <a href="{{ route('admin.categories.attributes.index', $category->id) }}" class="btn btn-default btn-sm">
                                            <i class="zmdi zmdi-ruler"></i>
                                        </a>
                                        <a href="{{ route('admin.categories.show', $category->id) }}" class="btn btn-info btn-sm">
                                            <i class="zmdi zmdi-labels"></i>
                                        </a>
                                        <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-sm">
                                            <i class="zmdi zmdi-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    {{ $categories->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h2><strong>{{ $title }}</strong></h2>
                    <br>
                    <h2><a href="{{ route('admin.products.create') }}" class="btn btn-light">Добавить товар</a></h2>
                </div>
            </div>
        </div>
        @foreach($products as $product)
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                <div class="card">
                    <div class="body product_item">
                        <img src="{{ $product->image->image }}" alt="Product" class="img-fluid cp_img" />
                        <div class="product_details">
                            <a href="{{ route('admin.products.edit', $product->id) }}">{{ $product->name }}</a>
                            <ul class="product_price list-unstyled">
                                <li class="new_price">{{ $product->price }}</li>
                            </ul>
                        </div>
                        <div class="action">
                            <a href="{{ route('admin.products.attributes.index', $product->id) }}" class="btn btn-default waves-effect">
                                <i class="zmdi zmdi-ruler"></i>
                            </a>
                            <a href="{{ route('admin.products.edit', $product->id) }}" class="btn btn-info waves-effect">
                                <i class="zmdi zmdi-edit"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach

        {{ $products->links() }}
    </div>
@endsection